# Generated by Django 3.2.16 on 2023-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
