# Generated by Django 3.2.16 on 2023-08-23 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_produto_quantidade_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_disponivel',
        ),
    ]
